### ISSUE TITLE
Tables not rendered with nice style

### ISSUE THREAD

**Issue by nicola** [asg017/atom-observable#6]
It would be great to render tables with the same style!

**Comment by asg017** [comment]
Thanks for the issue!

This one will be a little hard to solve - a good chunk of notebook styling on observablehq.com is copyrighted to Observable Inc. and is only available if you copy/paste directly from their compiled HTML `<style>` tags. The Inspector CSS is [open sourced](https://github.com/observablehq/inspector/blob/master/src/style.css) (for things like inspector arrays, object, etc.) and is already used in this Atom package, but it doesn't provide styling for markdown elements (table styles, code blocks, etc).

For a quick fix, I've made `v0.4.1` that defaults to [github markdown styling](https://github.com/sindresorhus/github-markdown-css). Ideally, I think we should have our own custom styling that more closely resembles observablehq styling and that can be used in other Observable extensions (VS Code, standalone apps, etc.), but I think Github Markdown styling is "good enough" for now.

Let me know if you like the new styling! If there's more desire from others for more observablehq-like styled components, then I'll make a new issue to track that.

**Comment by nicola** [comment]
awesome! I consider this resolved
